### ISSUE TITLE
new buttons (beta) objections/opinions

### ISSUE THREAD

**Issue by nazrhyn** [mallowigi/material-theme-jetbrains#14]
First, thanks for picking this project up; it's been awesome seeing it actually get updates again!

As for the new buttons:   
![image](https://cloud.githubusercontent.com/assets/1672405/25342071/d366174c-28d8-11e7-97d8-f23c9cb6a358.png)   
![image](https://cloud.githubusercontent.com/assets/1672405/25342082/da2e7614-28d8-11e7-9887-413fe396cbbf.png)   
![image](https://cloud.githubusercontent.com/assets/1672405/25342101/eb3c42ce-28d8-11e7-8daa-70cf5d632eb8.png)

Removing the borders causes some of the same problem that we see in buttons in Apple's interfaces post skeumorphism crusade and in some material design scenarios:
* It's not clear that they're buttons until you attempt to interact with them.
* It's not clear where the edge of the interactable space is until you attempt to interact with them.
* When it looks like they're just text, the vertical alignment of the text is now (in my opinion) visually "expected" to be at the same baseline as other things around it. For example, in the **Update Project** dialog, I now expect the buttons' text baseline to align with the "Do not show this dialog in the future" text.

At the very least, the at-rest background color/tone should be different than the background they're sitting on to avoid these problems.

These are, of course, just my opinions :smile:.

Thanks, again!

**Comment by mallowigi** [comment]
I agree with your opinions, but this is a choice I've made with incorporating Material Design guidelines into this project. Maybe at some point I'll also insert the concept of raised buttons/primary buttons to contrast with the background - for instance in the update dialog at the very least a call to action should be visible through a primary button. It also depends on what the IntelliJ SDK is letting me do with it :)

Also, for now I'm taking inspiration from the Sublime Text plugin, so at the very least it should mimic its features and not deviate too much. The color between the buttons and other components are mainly because the other components colors are not the right ones. At some point I might want to change them to be white only on hover or when a checkbox is checked. But this is not the priority at the moment, and the buttons was just a nice touch to experiment what we can do with the plugin SDK :)

Thanks for the remarks though 🥇

**Comment by nazrhyn** [comment]
I don't suppose you'd be interested in making it configurable? The un-delineated buttons thing is just such a pet peeve of mine. I'll probably just end up getting stuck on the version previous to this one forever because I like the rest of this project so much outside of that. :smile:

**Comment by mallowigi** [comment]
Theoretically it should be possible to make it configurable, I'll think of something in the future :)

--
Elior Boukhobza

**Comment by nazrhyn** [comment]
My hero.
